### ISSUE TITLE
Generate tags (not branches) for new releases

### ISSUE THREAD

**Issue by aldesantis** [solidusio/solidus_dev_support#67]
The correct configuration looks like this:

```yaml
bump:
  recurse: false
  file: 'lib/solidus_support/version.rb'
  message: Bump SolidusSupport to %{version}
  branch: false
  tag: true
```
